"""add name 

Revision ID: 07cb14cbcb3b
Revises: f807a89a2bba
Create Date: 2024-02-29 22:09:35.288327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07cb14cbcb3b'
down_revision: Union[str, None] = 'f807a89a2bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'name')
    # ### end Alembic commands ###
