"""Unique workflow name

Revision ID: 6da8c76fcf0f
Revises: 07cb14cbcb3b
Create Date: 2024-03-01 08:24:25.346885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da8c76fcf0f'
down_revision: Union[str, None] = '07cb14cbcb3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'workflow', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow', type_='unique')
    # ### end Alembic commands ###
