"""Add label field

Revision ID: 77582bbe89aa
Revises: fe1a62777c34
Create Date: 2024-03-04 14:39:23.172708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77582bbe89aa'
down_revision: Union[str, None] = 'fe1a62777c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edges', sa.Column('label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edges', 'label')
    # ### end Alembic commands ###
