"""empty message

Revision ID: fe1a62777c34
Revises: e775ef1cb7bc
Create Date: 2024-03-04 14:12:17.473941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1a62777c34'
down_revision: Union[str, None] = 'e775ef1cb7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_edge', 'edges', ['from_node_id', 'to_node_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_edge', 'edges', type_='unique')
    # ### end Alembic commands ###
